name: deploy_to_s3

on: 
  push:
    branches:
      - s3-deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true
      
      - name: Install node modules
        working-directory: website
        run: npm install

      - name: Build
        working-directory: website
        run: hugo --minify --gc
      
      - name: prepare terraform
        uses: hashicorp/setup-terraform@v2

      - name: init terraform
        working-directory: terraform
        run: terraform init

      - id: plan
        name: plan terraform
        working-directory: terraform
        run: terraform plan -no-color

      - name: deploy with terraform
        working-directory: terraform
        run: terraform apply --auto-approve