name: deploy_to_s3

on: 
  push:
    branches:
      - s3-deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true
      
      - name: Build
        run: |
          (cd website
          npm install
          hugo --minify --gc)
      
      - name: prepare terraform
        uses: hashicorp/setup-terraform@v2

      - run: |
          cd terraform
          terraform init

      - id: plan
        run: |
          cd terraform
          terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

      - run: |
          cd terraform
          terraform apply --auto-approve